"""initial migration with all models including user_id

Revision ID: a9383cb340e4
Revises: 
Create Date: 2025-07-01 19:06:26.256965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9383cb340e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('business_number', sa.String(), nullable=False),
    sa.Column('representative', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('bank_account', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('bank_info', sa.JSON(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_business_number'), 'vendors', ['business_number'], unique=True)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='프로젝트명'),
    sa.Column('project_number', sa.String(length=50), nullable=False, comment='프로젝트 번호'),
    sa.Column('description', sa.Text(), nullable=True, comment='프로젝트 설명'),
    sa.Column('project_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INFRASTRUCTURE', 'INDUSTRIAL', 'MIXED_USE', 'OTHER', name='projecttype'), nullable=False, comment='프로젝트 유형'),
    sa.Column('status', sa.Enum('PLANNING', 'PREPARATION', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', 'CANCELLED', name='projectstatus'), nullable=False, comment='프로젝트 상태'),
    sa.Column('location', sa.String(length=500), nullable=True, comment='프로젝트 위치'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='상세 주소'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='시작일'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='종료일'),
    sa.Column('planned_start_date', sa.DateTime(), nullable=True, comment='계획 시작일'),
    sa.Column('planned_end_date', sa.DateTime(), nullable=True, comment='계획 종료일'),
    sa.Column('total_budget', sa.Float(), nullable=True, comment='총 예산'),
    sa.Column('current_cost', sa.Float(), nullable=True, comment='현재 비용'),
    sa.Column('remaining_budget', sa.Float(), nullable=True, comment='잔여 예산'),
    sa.Column('project_manager', sa.String(length=100), nullable=True, comment='프로젝트 매니저'),
    sa.Column('client_name', sa.String(length=255), nullable=True, comment='발주처명'),
    sa.Column('client_contact', sa.String(length=100), nullable=True, comment='발주처 연락처'),
    sa.Column('building_area', sa.Float(), nullable=True, comment='건축면적 (㎡)'),
    sa.Column('floor_area', sa.Float(), nullable=True, comment='연면적 (㎡)'),
    sa.Column('floors', sa.Integer(), nullable=True, comment='층수'),
    sa.Column('vendor_id', sa.String(), nullable=True, comment='거래처 ID'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_project_number'), 'projects', ['project_number'], unique=True)
    op.create_table('vendor_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='계약명'),
    sa.Column('contract_number', sa.String(length=50), nullable=False, comment='계약번호'),
    sa.Column('contract_amount', sa.Float(), nullable=False, comment='계약금액'),
    sa.Column('contract_date', sa.DateTime(), nullable=False, comment='계약일'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='시작일'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='종료일'),
    sa.Column('client_name', sa.String(length=255), nullable=False, comment='발주처명'),
    sa.Column('client_contact', sa.String(length=100), nullable=True, comment='발주처 연락처'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='계약 상태'),
    sa.Column('description', sa.Text(), nullable=True, comment='계약 설명'),
    sa.Column('vendor_id', sa.String(), nullable=False, comment='거래처 ID'),
    sa.Column('project_id', sa.String(), nullable=True, comment='프로젝트 ID'),
    sa.Column('user_id', sa.String(), nullable=True, comment='사용자 ID'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_contracts_name'), 'contracts', ['name'], unique=False)
    op.create_table('project_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='문서 제목'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='파일명'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='파일 경로'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='파일 크기 (bytes)'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='파일 유형'),
    sa.Column('document_type', sa.String(length=100), nullable=True, comment='문서 유형'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='문서 카테고리'),
    sa.Column('description', sa.Text(), nullable=True, comment='문서 설명'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='태그 (쉼표로 구분)'),
    sa.Column('version', sa.String(length=20), nullable=True, comment='문서 버전'),
    sa.Column('project_id', sa.String(), nullable=False, comment='프로젝트 ID'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False, comment='계약 ID'),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment='문서 유형'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='파일 경로'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='파일명'),
    sa.Column('upload_date', sa.DateTime(), nullable=True, comment='업로드일'),
    sa.Column('description', sa.Text(), nullable=True, comment='문서 설명'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True, comment='사용자 ID'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('id_number', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_account', sa.String(), nullable=True),
    sa.Column('daily_wage', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True, comment='사용자 ID'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_number')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_table('financial_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('financial_record_id', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['financial_record_id'], ['financial_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('labor_id', sa.String(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('work_hours', sa.Float(), nullable=True),
    sa.Column('daily_wage', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['labor_id'], ['labors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_logs')
    op.drop_table('financial_documents')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('labors')
    op.drop_table('financial_records')
    op.drop_table('contract_documents')
    op.drop_table('project_documents')
    op.drop_index(op.f('ix_contracts_name'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('vendor_documents')
    op.drop_index(op.f('ix_projects_project_number'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_business_number'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
